version: "3.8"
services:
  postgres:
    container_name: postgres
    restart: always
    image: "postgres:11"
    user: postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/crudapp
    volumes:
      - db_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
          max-size: "10k"
          max-file: "10"
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    expose: 
      - "8000"
    ports:
      - "${PYTHON_API_PORT:-8080}:8080"
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
    command: bash -c "python3 manage.py makemigrations; python3 manage.py migrate; /usr/local/bin/python3 -u manage.py runserver 0.0.0.0:8080"
    logging:
      driver: "json-file"
      options:
          max-size: "10k"
          max-file: "10"
volumes: 
  db_data:

